### Tüm kullanıcıları listele
GET http://localhost:3003/users

### Yeni kullanıcı oluştur
POST http://localhost:3003/users
Content-Type: application/json

{
  "name": "Test Kullanıcı",
  "email": "testuser@example.com",
  "password": "123456"
}
